package util;

public enum NetworkCommands {
    LOGIN, CONFIRM_AUTHORIZATION, REJECT_AUTHORIZATION,
    LOGOUT,
    DEPOSIT, CONFIRM_DEPOSIT, REJECT_DEPOSIT,
    WITHDRAW, CONFIRM_WITHDRAWAL, REJECT_WITHDRAWAL
}
